Repository bcgov/moh-pidp, pull requests merged in 2024-10, with the labels that each got.

#599 PIDP-1062 Fix Console error
  workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.html
  workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.ts
Labels: Ready For Review

#605 Add Patroni for Gold and Golddr clusters
  infra/patroni-gold-golddr/README.md
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/.helmignore
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/Chart.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/FailBack.md
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/README.md
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/templates/_helpers.tpl
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/templates/configmap.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/templates/cronjobs.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/templates/networkpolicy.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/templates/rbac.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/templates/secret.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/templates/services.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/templates/statefulsets.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/templates/transportserverclaim.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/values-gold.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/values-golddr.yaml
Labels: DevOps, Ready For Review

#596 PIDP-1058 Run status change for new PLR records
  backend/services.plr-intake.tests/.vscode/settings.json
  backend/services.plr-intake.tests/Features/Intake/IntakeService.cs
  backend/services.plr-intake/Features/Intake/IntakeService.cs
Labels: Ready For Review

#612 Silver to gold-more edits
  .github/workflows/main-deploy-endorsement-reminder.yaml
  .github/workflows/pr-build-gold.yaml
  .github/workflows/test-deploy_helm_chart.yaml
  charts/frontend/templates/deployment.yaml
  charts/frontend/values.yaml
  charts/pidp/values.yaml
  charts/plr-intake/templates/deployment.yaml
  charts/plr-intake/values.yaml
  charts/webapi/templates/deployment.yaml
  charts/webapi/values.yaml
  deploy/dev_values.yaml
  deploy/pr_values.yaml
  deploy/prod_values_gold.yaml
  deploy/test_values.yaml
Labels: Ready For Review

#607 Pidp 897 add keywords for cards
  workspace/apps/pidp/src/app/features/access/pages/access-requests-page/access-requests.page.ts
  workspace/apps/pidp/src/app/features/portal/state/access-section.model.ts
  workspace/apps/pidp/src/app/features/portal/state/access/account-linking-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/bc-provider-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/driver-fitness-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/hcim-account-transfer-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/immsbc-eforms-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/ms-teams-clinic-member-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/ms-teams-privacy-officer-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/prescription-refill-eforms-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/provider-reporting-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/provincial-attachment-system-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/access/sa-eforms-portal-section.class.ts
  workspace/apps/pidp/src/app/features/portal/state/section.model.ts
Labels: Ready For Review

#602 Pidp 1047/1048 window scroll console error&open multiple dialogs
  workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/user-access-agreement.page.spec.ts
  workspace/libs/shared/ui/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html
  workspace/libs/shared/ui/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.ts
Labels: Ready For Review

#610 Pidp-1056 Back to top misalignment
  workspace/apps/pidp/src/app/features/access/pages/access-requests-page/access-requests.page.scss
  workspace/apps/pidp/src/app/features/faq/pages/help/help.page.scss
  workspace/apps/pidp/src/app/features/faq/pages/mfa-setup/mfa-setup.page.scss
  workspace/apps/pidp/src/app/features/portal/portal.page.scss
Labels: Ready For Review

#600 Pidp 1044 banner for server outage notification
  workspace/apps/pidp/src/app/features/auth/pages/login/banner-find.response.model.ts
  workspace/apps/pidp/src/app/features/auth/pages/login/login-resource.service.spec.ts
  workspace/apps/pidp/src/app/features/auth/pages/login/login-resource.service.ts
  workspace/apps/pidp/src/app/features/auth/pages/login/login.constants.ts
  workspace/apps/pidp/src/app/features/auth/pages/login/login.page.html
  workspace/apps/pidp/src/app/features/auth/pages/login/login.page.scss
  workspace/apps/pidp/src/app/features/auth/pages/login/login.page.spec.ts
  workspace/apps/pidp/src/app/features/auth/pages/login/login.page.ts
  workspace/apps/pidp/src/app/shared/components/banner/banner.component.html
  workspace/apps/pidp/src/app/shared/components/banner/banner.component.scss
  workspace/apps/pidp/src/app/shared/components/banner/banner.component.spec.ts
  workspace/apps/pidp/src/app/shared/components/banner/banner.component.ts
  workspace/apps/pidp/src/assets/images/icons/icon-warning.svg
Labels: Ready For Review

#613 Fix - DMFT update to link
  workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.constants.ts
  workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.page.ts
Labels: Ready For Review

#618 PIDP-1089 When PAS is completed show green icon
  workspace/apps/pidp/src/app/features/portal/state/access/provincial-attachment-system-portal-section.class.ts
Labels: Ready For Review

#617 upgrade the helm charts
  .github/workflows/dev-deploy-helm_chart.yaml
  .github/workflows/main-deploy-db-migration.yaml
  charts/pidp/charts/frontend-0.1.1.tgz
  charts/pidp/charts/plr-intake-0.1.2.tgz
  charts/pidp/charts/webapi-0.1.5.tgz
  deploy/prod_values.yaml
  infra/patroni-gold-golddr/helm/patroni-gold-golddr/FailBack.md
Labels: DevOps
